name: Deploy to Another Repository

on:
  push:
    branches:
      - main  # Replace with your development branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2

    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Checkout Target Repository
      uses: actions/checkout@v2
      with:
        repository: 'username/target-repository-name'  # Replace with your target repository
        token: ${{ secrets.TARGET_REPO_TOKEN }}  # PAT stored as a secret
        path: 'target-repo'  # Directory to checkout the repository

    - name: Copy Files to Target Repository
      run: |
        cp -r ./build/* ./target-repo/specific-folder/  # Replace with your specific folder

    - name: Commit and Push
      run: |
        cd target-repo
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Deploying built application"
        git push
